### ISSUE TITLE
Civo CLI download config error.

### ISSUE THREAD

**Issue by will2therich** [civo/kube100#2]
Not sure If I have done something wrong here but upon trying to download a config to my windows machine using the latest Civo CLI I get the following message.

Any ideas?
![image](https://user-images.githubusercontent.com/24435180/65778441-d1c34200-e13d-11e9-8a4e-b6759d20695f.png)

**Comment by andyjeffries** [comment]
@kaihoffman this is part of a bigger review that we need to do - testing the CLI on Windows. This area of code in particular is trying to do file merging stuff using Unix style `/` rather than Windows style `\`. So could you give it a thorough run through on Windows sometime (VM - https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) and fix any issues (this may be useful too - http://www.java2s.com/Code/Ruby/Development/EasyOSDetectionwithRUBYPLATFORM.htm).

**Comment by kaihoffman** [comment]
Fixed in version 0.4.6. Closing.
