### ISSUE TITLE
Master time out, cluster appears unresponsive....

### ISSUE THREAD

**Issue by james-devr** [civo/kube100#22]
https://185.136.232.249:6443
cluster: civo-test

This is second time I've broken the master today. I just deleted the cluster and started again but it's happened a second time round

**Comment by andyjeffries** [comment]
Can you give more details on how you've broken it? What were you doing at the time? (you wrote "I've broken" rather than "the cluster broke while I wasn't touching it", so I'm guessing you've done something).

Out of interest, what size nodes are you using? There can be issues if you run really resource intensive apps (even from the marketplace) on XS instances. We let you launch XS instances for playing with k3s, but it doesn't mean an XS machine will run everything.
